services:
  - type: web_service
    name: foodprep-backend
    repo: VK-SHRIDHARAN/23BCE2086_FSD
    branch: master
    env: node
    plan: free
    region: oregon
    root: backend
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: DB_URI
        value: "<SET_IN_DASHBOARD>"
      - key: JWT_TOKEN_SECRET
        value: "<SET_IN_DASHBOARD>"
      - key: STRIPE_SECRET_KEY
        value: "<SET_IN_DASHBOARD>"
      - key: FRONTEND_URL
        value: "https://food-prep-frontend.onrender.com"

  - type: static_site
    name: foodprep-user-frontend
    repo: VK-SHRIDHARAN/23BCE2086_FSD
    branch: master
    plan: free
    root: userfrontend
    buildCommand: npm ci && npm run build
    publish: dist
    envVars:
      - key: VITE_API_URL
        value: "<SET_IN_DASHBOARD>"

  - type: static_site
    name: foodprep-admin-frontend
    repo: VK-SHRIDHARAN/23BCE2086_FSD
    branch: master
    plan: free
    root: adminfrontend
    buildCommand: npm ci && npm run build
    publish: dist
    envVars:
      - key: VITE_API_URL
        value: "<SET_IN_DASHBOARD>"
